# Configuration file for Mid Lancs Track & Field League Scraper

[scraper]
# The base URL to scan for Mid Lancs Track & Field League pages
url = "https://www.race-results.co.uk/results/2025/#9"

# The search text to look for in links (case-insensitive)
search_text = "Mid Lancs Track & Field League"

[events]
# Keywords to identify track events (case-insensitive)
track_keywords = [
    "100m", "200m", "400m", "800m", "1500m", "3000m", "5000m",
    "100m hurdles", "110m hurdles", "400m hurdles",
    "sprint", "relay", "4x100m", "4x400m", "steeplechase"
]

# Keywords to identify field events (case-insensitive)
field_keywords = [
    "long jump", "high jump", "triple jump", "pole vault",
    "shot put", "discus", "javelin", "hammer", "shot",
    "lj", "hj", "tj", "pv"
]

[output]
# Width of the club name column in the output table
club_column_width = 40

# Width of the athlete count columns
count_column_width = 15

# How to sort the club statistics table
# Options: "alphabetical" (sort by club name A-Z) or "numerical" (sort by participation, highest first)
sort_by = "alphabetical"

# Excel output file path (relative to project directory or absolute path)
# Set to empty string "" to disable Excel output
excel_output_path = "mid_lancs_results.xlsx"
