[project]
name = "mid-lancs-scraper"
version = "0.1.0"
description = "Scraper for Mid Lancs Track & Field League athletics results"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "requests>=2.31.0",
    "beautifulsoup4>=4.12.0",
    "pandas>=2.0.0",
    "openpyxl>=3.0.0",
]
